apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc-lokesh6694 # Replace 'jegan' with your name
spec:
  selector:
    matchLabels:
      name: lokesh6694 # Replace 'jegan' with your name
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
