apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-lokesh6694 # Replace 'jegan' with your name
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
