apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-lokesh6694 # Replace 'jegan' with your name
  labels:
    name: lokesh6694 # Replace 'jegan' with your name
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.15.62 # Replace this IP with Server1(10.10.15.32) or Server2(10.10.15.8) or Server3(10.10.15.27) dependending on your linux user 
    path: /var/nfs/user05/share2 # Replace this path with /mnt/nfs/user1/mysql folder
