apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-lokesh6694 # Replace 'jegan' with your name
  labels:
    name: lokesh6694 # Replace 'jegan' with your name
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.15.62 # Replace this IP with 10.10.15.61 or 10.10.15.62 or 10.10.15.63 depending on your linux user 
    path: /var/nfs/user05/share5 # Replace this path with /var/nfs/user01/share2 folder
