apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-lokesh6694 # Replace 'jegan' with your name
  labels:
    name: lokesh6694 # Replace 'jegan' with your name
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.15.62 # Replace this IP with your CentOS IP
    path: /var/nfs/user05/share4 # Replace this path with /mnt/nfs/user1/wordpress folder, replace user1 with your centos username 
